String cityMunicipalityProvince = "Agusan del Norte,Buenavista,Butuan,"
    "Cabadbaran,Carmen,Jabonga,Kitcharao,Las Nieves,Magallanes,Nasipit,"
    "Remedios T. Romualdez,Santiago,Tubay,Agusan del Sur,Bayugan,Bunawan,"
    "Esperanza,La Paz,Loreto,Prosperidad,Rosario,San Francisco,San Luis,Santa "
    "Josefa,Sibagat,Talacogon,Trento,Veruela,Basilan,Akbar,Al-Barka,Hadji "
    "Mohammad Ajul,Hadji Muhtamad,Lamitan,Lantawan,Maluso,Sumisip,Tabuan-Lasa,"
    "Tipo-Tipo,Tuburan,Ungkaya Pukan,Bukidnon,Baungon,Cabanglasan,Damulog,"
    "Dangcagan,Don Carlos,Impasug-ong,Kadingilan,Kalilangan,Kibawe,Kitaotao,"
    "Lantapan,Libona,Malaybalay,Malitbog,Manolo Fortich,Maramag,Pangantucan,"
    "Quezon,San Fernando,Sumilao,Talakag,Valencia,Camiguin,Catarman,Guinsiliban,"
    "Mahinog,Mambajao,Sagay,City of Isabela,Isabela,Compostela Valley,Compostela,"
    "Laak \(San Vicente\),Mabini \(Doña Alicia\),Maco,Maragusan \(San Mariano\),"
    "Mawab,Monkayo,Montevista,Nabunturan,New Bataan,Pantukan,Cotabato \(North Cotabato\),"
    "Alamada,Aleosan,Antipas,Arakan,Banisilan,Carmen,Kabacan,Kidapawan,Libungan,Magpet,"
    "Makilala,Matalam,Midsayap,M'lang,Pigkawayan \(Pigcawayan\),Pikit,President Roxas,"
    "Tulunan,Cotabato City,Cotabato,Davao del Norte,Asuncion \(Saug\),Braulio E. Dujali,"
    "Carmen,Kapalong,New Corella,Panabo,Samal \(Island Garden City of Samal\),San Isidro,"
    "Santo Tomas,Tagum,Talaingod,Davao del Sur,Bansalan,Davao,Digos,Hagonoy,Kiblawan,Magsaysay,"
    "Malalag,Matanao,Padada,Santa Cruz,Sulop,Davao Occidental,Don Marcelino,Jose Abad Santos \(Trinidad\),"
    "Malita,Santa Maria,Sarangani,Davao Oriental,Baganga,Banaybanay,Boston,Caraga,Cateel,"
    "Governor Generoso,Lupon,Manay,Mati,San Isidro,Tarragona,Dinagat Islands,Basilisa \(Rizal\),"
    "Cagdianao,Dinagat,Libjo \(Albor\),Loreto,San Jose,Tubajon,Lanao del Norte,"
    "Bacolod,Baloi \(Balo-i\),Baroy,Iligan,Kapatagan,Kauswagan,Kolambugan,Lala,Linamon,"
    "Magsaysay,Maigo,Matungao,Munai,Nunungan,Pantao Ragat,Pantar,Poona Piagapo,Salvador,"
    "Sapad,Sultan Naga Dimaporo \(Karomatan\),Tagoloan,Tangcal,Tubod,Lanao del Sur,"
    "Bacolod-Kalawi \(Bacolod Grande\),Balabagan,Balindong \(Watu\),Bayang,Binidayan,"
    "Buadiposo-Buntong,Bubong,Bumbaran \(Amai Manabilang\),Butig,Calanogas,Ditsaan-Ramain,"
    "Ganassi,Kapai,Kapatagan,Lumba-Bayabao \(Maguing\),Lumbaca-Unayan,Lumbatan,"
    "Lumbayanague,Madalum,Madamba,Maguing,Malabang,Marantao,Marawi,Marogong,Masiu,"
    "Mulondo,Pagayawan \(Tatarikan\),Piagapo,Picong \(Sultan Gumander\),Poona Bayabao \(Gata\),"
    "Pualas,Saguiaran,Sultan Dumalondong,Tagoloan II,Tamparan,Taraka,Tubaran,Tugaya,Wao,"
    "Maguindanao,Ampatuan,Barira,Buldon,Buluan,Datu Abdullah Sangki,Datu Anggal Midtimbang,"
    "Datu Blah T. Sinsuat,Datu Hoffer Ampatuan \(← Shariff Aguak\),Datu Odin Sinsuat \(Dinaig\),"
    "Datu Paglas,Datu Piang,Datu Salibo \(← Datu Piang\),Datu Saudi-Ampatuan,Datu Unsay,"
    "General Salipada K. Pendatun,Guindulungan,Kabuntalan \(Tumbao\),Mamasapano,Mangudadatu,"
    "Matanog,Northern Kabuntalan,Pagagawan \(Datu Montawal\),Pagalungan,Paglat,Pandag,Parang,"
    "Rajah Buayan,Shariff Aguak \(Maganoy\),Shariff Saydona Mustapha,South Upi,Sultan Kudarat \(Nuling\),"
    "Sultan Mastura,Sultan sa Barongis \(Lambayong\),Talayan,Talitay \(Sultan Sumagka\),"
    "Upi,Misamis Occidental,Aloran,Baliangao,Bonifacio,Calamba,Clarin,Concepcion,"
    "Don Victoriano Chiongbian \(Don Mariano Marcos\)	,Jimenez,Lopez Jaena,Oroquieta,"
    "Ozamis \(Ozamiz\),Panaon,Plaridel,Sapang Dalaga,Sinacaban,Tangub,Tudela,Misamis Oriental,"
    "Alubijid,Balingasag,Balingoan,Binuangan,Cagayan de Oro,Claveria,El Salvador,"
    "Gingoog,Gitagum,Initao,Jasaan,Kinoguitan,Lagonglong,Laguindingan,Libertad,Lugait,"
    "Magsaysay \(Linugos\),Manticao,Medina,Naawan,Opol,Salay,Sugbongcogon,Tagoloan,"
    "Talisayan,Villanueva,Sarangani,Alabel,Glan,Kiamba,Maasim,Maitum,Malapatan,Malungon,"
    "South Cotabato,Banga,General Santos \(Dadiangas\),Koronadal,Lake Sebu,Norala,Polomolok,"
    "Santo Niño,Surallah,Tampakan,Tantangan,T'Boli,Tupi,Sultan Kudarat,Bagumbayan,Columbio,"
    "Esperanza,Isulan,Kalamansig,Lambayong \(Mariano Marcos\),Lebak,Lutayan,Palimbang,"
    "President Quirino,Senator Ninoy Aquino \(Senator Ninoy Aquino\),Tacurong,Sulu,"
    "Hadji Panglima Tahil \(Marunggas\),Indanan,Jolo,Kalingalan Caluang,Lugus,Luuk,"
    "Maimbung,Old Panamao,Omar,Pandami,Panglima Estino \(New Panamao\),Pangutaran,"
    "Parang,Pata,Patikul,Siasi,Talipao,Tapul,Tongkil \(Banguingui\),Surigao del Norte,"
    "Alegria,Bacuag,Burgos,Claver,Dapa,Del Carmen,General Luna,Gigaquit,Mainit,Malimono,"
    "Pilar,Placer,San Benito,San Francisco \(Anao-Aon\),San Isidro,Santa Monica \(Sapao\),"
    "Sison,Socorro,Surigao,Tagana-an,Tubod,Surigao del Sur,Barobo,Bayabas,Bislig,Cagwait,"
    "Cantilan,Carmen,Carrascal,Cortes,Hinatuan,Lanuza,Lianga,Lingig,Madrid,Marihatag,"
    "San Agustin,San Miguel,Tagbina,Tago,Tandag,Tawi-Tawi,Bongao,Languyan,Mapun \(Cagayan de Tawi-Tawi\),"
    "Panglima Sugala \(Balimbing\),Sapa-Sapa,Sibutu,Simunul,Sitangkai,South Ubian,"
    "Tandubas,Turtle Islands,Zamboanga del Norte,Bacungan \(Leon T. Postigo\),"
    "Baliguian,Dapitan,Dipolog,Godod,Gutalac,Jose Dalman \(Ponot\),Kalawit,Katipunan,"
    "Labason,La Libertad,Liloy,Manukan,Mutia,Piñan \(New Piñan\),Polanco,"
    "President Manuel A. Roxas,Rizal,Salug,Sergio Osmeña Sr.,Siayan,Sibuco,Sibutad,"
    "Sindangan,Siocon,Sirawai,Tampilisan,Zamboanga del Sur,Aurora,Bayog,Dimataling,"
    "Dinas,Dumalinao,Dumingag,Guipos,Josefina,Kumalarang,Labangan,Lakewoo,Lapuyan,"
    "Mahayag,Margosatubig,Midsalip,Molave,Pagadian,Pitogo,Ramon Magsaysay \(Liargo\),"
    "San Miguel,San Pablo,Sominot \(Don Mariano Marcos\),Tabina,Tambulig,Tigbao,"
    "Tukuran,Vincenzo A. Sagun,Zamboanga,Zamboanga Sibugay,Alicia,Buug,Diplahan,"
    "Imelda,Ipil,Kabasalan,Mabuhay,Malanga,Naga,Olutanga,Payao,Roseller Lim,Siay,"
    "Talusan,Titay,Tungawan";

class CityProvinceMunicipality {
  static List<String> getItems = cityMunicipalityProvince.split(',');
}
